; The Laravel scheduler: tweets:generate every ten minutes, tweets:prune daily
[program:laravel-scheduler]
command=php /app/artisan schedule:work
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
numprocs=1
startsecs=0
stdout_logfile=/var/log/laravel-scheduler.log
stderr_logfile=/var/log/laravel-scheduler.log
